import './globals.css'
import { Quattrocento_Sans } from 'next/font/google'
import Header from '@/components/navbar'

const quattro = Quattrocento_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-body',
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={quattro.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
